version: '3' 
services:
  postgres:
     container_name: postgresql
     image: postgres:13
     restart: always
     environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin
     ports:
        - 5432:5432
  pgadmin:
     container_name: pgadmin4
     image: dpage/pgadmin4:6.1
     restart: always
     environment:
        PGADMIN_DEFAULT_EMAIL: "postgres@admin.com.br"
        PGADMIN_DEFAULT_PASSWORD: "admin"
     ports:
         - "4000:80"
