version: '3'
services:

  #############################################################
  ######################### DATABASES #########################
  #############################################################

  mysql:
    container_name: db-mysql
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_USER: developer
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: SYM{]8rpd;q6:+V
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql


volumes:
    mysql:
